### ISSUE TITLE
Not working on Django 2.0.1 

### ISSUE THREAD

**Issue by gurugeek** [nesdis/djongo#54]
#### One line description of the issue
seems not to work in Django 2.0.1 
#### Traceback
<The complete stack trace of the error.>

Request Method: | POST
-- | --
http://c/admin/login/?next=/admin/
2.0.1
AttributeError
'DatabaseOperations' object has no attribute 'bulk_insert_sql'
/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py in as_sql, line 1265
/usr/local/bin/python3
3.6.1
['/home/gurugeek/django',  '/usr/local/bin',  '/home/gurugeek/django',  '/usr/home/gurugeek/django',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
Sun, 21 Jan 2018 18:26:03 +0000

Traceback Switch to copy-and-paste view

/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py in login
        return LoginView.as_view(**defaults)(request) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/views/generic/base.py in view
            return self.dispatch(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py in sensitive_post_parameters_wrapper
            return view(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/utils/decorators.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/auth/views.py in dispatch
        return super().dispatch(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/views/generic/base.py in dispatch
        return handler(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py in post
            return self.form_valid(form) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/auth/views.py in form_valid
        auth_login(self.request, form.get_user()) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py in login
        request.session.cycle_key() ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py in cycle_key
        self.create() ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py in create
                self.save(must_create=True) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py in save
                obj.save(force_insert=must_create, force_update=not must_create, using=using) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/base.py in save
                       force_update=force_update, update_fields=update_fields) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/base.py in save_base
            updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/base.py in _save_table
            result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/base.py in _do_insert
                               using=using, raw=raw) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/manager.py in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/query.py in _insert
        return query.get_compiler(using=using).execute_sql(return_id) ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py in execute_sql
            for sql, params in self.as_sql(): ...
▶ Local vars
/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py in as_sql
            result.append(self.connection.ops.bulk_insert_sql(fields, placeholder_rows)) ...
▶ Local vars

**Comment by nesdis** [comment]
which version of djongo do u use

**Comment by gurugeek** [comment]
latest djongo==1.2.16

**Comment by nicorellius** [comment]
Just started a new project with Django 2.0.1, but I found this issue. Have you made any progress with this? I might try to get it running myself, but I'm sure others will want the Django 2.0.1 compatibility working anyway.

**Comment by nesdis** [comment]
Do you get the issue as above? The user reported that after reinstalling django in #55 the issue went away. Djongo is compatible with 2.0. There are no issues
